### ISSUE TITLE
Add --experimental_allow_proto3_optional support 

### ISSUE THREAD

**Issue by LiuDongxu-Vungle** [srikrsna/protoc-gen-gotag#14]
protoc v3.12.0 is going to add experimental support for the optional annotation to proto3 (see RC: https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.0-rc1). We may need to update our generator(s) (protoc-gen-grpc-gateway, protoc-gen-swagger). Doc for adding this ability is here: https://github.com/protocolbuffers/protobuf/blob/v3.12.0-rc1/docs/implementing_proto3_presence.md.

**Comment by srikrsna** [comment]
https://github.com/lyft/protoc-gen-star/issues/75

**Comment by xmlking** [comment]
I am stuck with missing **proto3 optional** support for **gotag** and  **protoc-gen-validate** plugins :) 
I think I should stop using _cutting edge_  
https://github.com/envoyproxy/protoc-gen-validate/issues/431

**Comment by k1ng440** [comment]
@srikrsna why this is closed? plugin still cant set tags to optional fields

**Comment by vtolstov** [comment]
Can you try to use protoc-gen-go-micro it supports setting tags

**Comment by srikrsna** [comment]
@k1ng440 Thank you for flagging it is now fixed in the latest release.

**Comment by Mexican-Man** [comment]
On the latest version 0.6.2 I'm still getting this error when using the `optional` keyword.

**Comment by srikrsna** [comment]
@Mexican-Man  The example in the project uses `optional` can you share more info on when it's not working. A small reproducible repo perhaps?

**Comment by xmlking** [comment]
I actually tied with latest version. It works now 
```proto
  optional string email = 10 [(tagger.tags) = "avro:\"email\" graphql:\"withNewTags,optional\"" ];
```
https://github.com/xmlking/grpc-starter-kit/blob/develop/proto/mkit/mkit/service/account/entities/v1/entities.proto#L25

Using with Buf tooling

**Comment by Mexican-Man** [comment]
> @Mexican-Man The example in the project uses `optional` can you share more info on when it's not working. A small reproducible repo perhaps?

You're right, it works fine. I tried the older releases, but none of them do what I'm experiencing... I'm going to look into my deps for anything outdated/weird (old version of protoc?).

In the mean time: whoops! Reject my pr, and I'll post back if I find anything.
